name: Run Tests

on:
  push:

jobs:
  tests:
    env:
      IMAGE_ID: patrickkesper/amira_blender_rendering/amira-ci-blender:test_workflow
    runs-on: ubuntu-20.04
    container: ghcr.io/$IMAGE_ID
    steps:
      - uses: actions/checkout@v2

      - run: /root/.bin/blender.d/2.91/python/bin/python3.7m -m pip install .
        name: Setup

      - run: python -m flake8 --format=pylint --output-file=flake8.log --tee
        name: Lint

      - run: scripts/run_tests --abr-path `pwd`
        name: Test

